/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addBlocks(Blockly) {
    Blockly.Blocks['microbit_k230Peripheral_k230InitUltrasound'] = {
        init: function () {
            this.jsonInit({
                colour: "#c282b5",
                colourSecondary: "#c27295",
                colourTertiary: "#c252a5",
                args0: [{
                        type: "field_dropdown",
                        name: "PINS",
                        options: [
                            [
                                "P2",
                                "2"
                            ],
                            [
                                "P3",
                                "3"
                            ],
                            [
                                "P4",
                                "4"
                            ],
                            [
                                "P5",
                                "5"
                            ],
                            [
                                "P6",
                                "6"
                            ],
                            [
                                "P14",
                                "14"
                            ],
                            [
                                "P15",
                                "15"
                            ],
                            [
                                "P16",
                                "16"
                            ],
                            [
                                "P17",
                                "17"
                            ],
                            [
                                "P18",
                                "18"
                            ],
                            [
                                "P19",
                                "19"
                            ],
                            [
                                "P26",
                                "26"
                            ],
                            [
                                "P27",
                                "27"
                            ],
                            [
                                "P32",
                                "32"
                            ],
                            [
                                "P33",
                                "33"
                            ],
                            [
                                "P34",
                                "34"
                            ],
                            [
                                "P35",
                                "35"
                            ],
                            [
                                "P36",
                                "36"
                            ],
                            [
                                "P37",
                                "37"
                            ],
                            [
                                "P40",
                                "40"
                            ],
                            [
                                "P41",
                                "41"
                            ],
                            [
                                "P42",
                                "42"
                            ],
                            [
                                "P46",
                                "46"
                            ],
                            [
                                "P47",
                                "47"
                            ],
                            [
                                "P48",
                                "48"
                            ],
                            [
                                "P49",
                                "49"
                            ],
                            [
                                "P52",
                                "52"
                            ],
                            [
                                "P61",
                                "61"
                            ]
                        ]
                    },
                    {
                        type: "field_dropdown",
                        name: "PINS1",
                        options: [
                            [
                                "P2",
                                "2"
                            ],
                            [
                                "P3",
                                "3"
                            ],
                            [
                                "P4",
                                "4"
                            ],
                            [
                                "P5",
                                "5"
                            ],
                            [
                                "P6",
                                "6"
                            ],
                            [
                                "P14",
                                "14"
                            ],
                            [
                                "P15",
                                "15"
                            ],
                            [
                                "P16",
                                "16"
                            ],
                            [
                                "P17",
                                "17"
                            ],
                            [
                                "P18",
                                "18"
                            ],
                            [
                                "P19",
                                "19"
                            ],
                            [
                                "P26",
                                "26"
                            ],
                            [
                                "P27",
                                "27"
                            ],
                            [
                                "P32",
                                "32"
                            ],
                            [
                                "P33",
                                "33"
                            ],
                            [
                                "P34",
                                "34"
                            ],
                            [
                                "P35",
                                "35"
                            ],
                            [
                                "P36",
                                "36"
                            ],
                            [
                                "P37",
                                "37"
                            ],
                            [
                                "P40",
                                "40"
                            ],
                            [
                                "P41",
                                "41"
                            ],
                            [
                                "P42",
                                "42"
                            ],
                            [
                                "P46",
                                "46"
                            ],
                            [
                                "P47",
                                "47"
                            ],
                            [
                                "P48",
                                "48"
                            ],
                            [
                                "P49",
                                "49"
                            ],
                            [
                                "P52",
                                "52"
                            ],
                            [
                                "P61",
                                "61"
                            ]
                        ]
                    }
                ],
                message0: "初始化超声波传感器，触发引脚 %1 - 接收引脚 %2",
                extensions: ['shape_statement']
            });
        }
    };


    Blockly.Blocks['microbit_k230Peripheral_k230ReadUltrasound'] = {
        init: function () {
            this.jsonInit({
                colour: "#c282b5",
                colourSecondary: "#c27295",
                colourTertiary: "#c252a5",
                args0: [{
                        type: "field_dropdown",
                        name: "PINS",
                        options: [
                            [
                                "P2",
                                "2"
                            ],
                            [
                                "P3",
                                "3"
                            ],
                            [
                                "P4",
                                "4"
                            ],
                            [
                                "P5",
                                "5"
                            ],
                            [
                                "P6",
                                "6"
                            ],
                            [
                                "P14",
                                "14"
                            ],
                            [
                                "P15",
                                "15"
                            ],
                            [
                                "P16",
                                "16"
                            ],
                            [
                                "P17",
                                "17"
                            ],
                            [
                                "P18",
                                "18"
                            ],
                            [
                                "P19",
                                "19"
                            ],
                            [
                                "P26",
                                "26"
                            ],
                            [
                                "P27",
                                "27"
                            ],
                            [
                                "P32",
                                "32"
                            ],
                            [
                                "P33",
                                "33"
                            ],
                            [
                                "P34",
                                "34"
                            ],
                            [
                                "P35",
                                "35"
                            ],
                            [
                                "P36",
                                "36"
                            ],
                            [
                                "P37",
                                "37"
                            ],
                            [
                                "P40",
                                "40"
                            ],
                            [
                                "P41",
                                "41"
                            ],
                            [
                                "P42",
                                "42"
                            ],
                            [
                                "P46",
                                "46"
                            ],
                            [
                                "P47",
                                "47"
                            ],
                            [
                                "P48",
                                "48"
                            ],
                            [
                                "P49",
                                "49"
                            ],
                            [
                                "P52",
                                "52"
                            ],
                            [
                                "P61",
                                "61"
                            ]
                        ]
                    },
                    {
                        type: "input_value",
                        name: "PINS1"
                    }
                ],
                message0: "读取触发引脚 %1 - 接收引脚 %2超声波探测的值",
                extensions: ['output_string']
            });
        }
    };

    return Blockly;
}

exports = addBlocks;
